### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-input-lumberjack#58]
From: http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20Inputs/job/logstash-plugin-input-lumberjack-unit/14/

```
Using bundler 1.10.6
Bundle complete! 5 Gemfile dependencies, 39 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.......F.......

Failures:

  1) LogStash::Inputs::Lumberjack#processing of events #codecs clone the codec per connection
     Failure/Error: lumberjack.run(queue)
     NoMethodError:
       undefined method `shutdown' for #<LogStash::Inputs::Lumberjack:0x36edcdeb>
     # ./lib/logstash/inputs/lumberjack.rb:95:in `run'
     # ./spec/inputs/lumberjack_spec.rb:46:in `(root)'

Finished in 6.3 seconds (files took 1.37 seconds to load)
15 examples, 1 failure

Failed examples:

rspec ./spec/inputs/lumberjack_spec.rb:43 # LogStash::Inputs::Lumberjack#processing of events #codecs clone the codec per connection

Randomized with seed 12389
```

**Comment by purbon** [comment]
Related to: #53 , but should not be the case, right?

**Comment by ph** [comment]
Thanks for bringing this up, #53 fix this by removing the shutdown.

The problematic test wasn't gracefully shutting down the plugin and since plugins doesn't have a `shutdown` anymore it made the test crash, I have changed the test a bit to make sure it stop the plugin once the test ran.

**Comment by ph** [comment]
#53 is merged
